In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot
from tensorflow.python.keras import Model
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.models import Sequential, Model
from tensorflow.python.keras.layers import Conv2D, Input, Dropout, Activation, Dense, MaxPooling2D, Flatten, GlobalAveragePooling2D
from keras.optimizers import adadelta_v2
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.layers import LSTM
import sklearn
from sklearn.preprocessing import MinMaxScaler

/usr/lib/python3/dist-packages/Crypto/Random/Fortuna/FortunaGenerator.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sys.version_info[0] is 2 and  sys.version_info[1] is 1:
/usr/lib/python3/dist-packages/Crypto/Random/Fortuna/FortunaGenerator.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sys.version_info[0] is 2 and  sys.version_info[1] is 1:


In [2]:
filepath = "../Data Preprocessing/iot23_combined.csv"
df = pd.read_csv(filepath)

In [3]:
df

Unnamed: 0  duration  orig_bytes  resp_bytes  missed_bytes  \
0                 0  2.998796           0           0           0.0   
1                 1  0.000000           0           0           0.0   
2                 2  0.000000           0           0           0.0   
3                 3  2.998804           0           0           0.0   
4                 4  0.000000           0           0           0.0   
...             ...       ...         ...         ...           ...   
2739669      198994  0.000000           0           0           0.0   
2739670      198995  0.000000           0           0           0.0   
2739671      198996  0.000000           0           0           0.0   
2739672      198997  0.000000           0           0           0.0   
2739673      198998  0.000000           0           0           0.0   

         orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes  label  ...  \
0              3.0          180.0        0.0            0.0      1  ...   
1              1.0           60.0        0.0            0.0      1  ...   
2              1.0           60.0        0.0            0.0      1  ...   
3              3.0          180.0        0.0            0.0      0  ...   
4              1.0           60.0        0.0            0.0      0  ...   
...            ...            ...        ...            ...    ...  ...   
2739669        1.0           40.0        0.0            0.0      1  ...   
2739670        1.0           40.0        0.0            0.0      1  ...   
2739671        1.0           40.0        0.0            0.0      1  ...   
2739672        1.0           40.0        0.0            0.0      1  ...   
2739673        1.0           40.0        0.0            0.0      1  ...   

        conn_state_SF  conn_state_SH  conn_state_SHR  service_-  service_dhcp  \
0                   0              0               0          1             0   
1                   0              0               0          1             0   
2                   0              0               0          1             0   
3                   0              0               0          1             0   
4                   0              0               0          1             0   
...               ...            ...             ...        ...           ...   
2739669             0              0               0          1             0   
2739670             0              0               0          1             0   
2739671             0              0               0          1             0   
2739672             0              0               0          1             0   
2739673             0              0               0          1             0   

         service_dns  service_http  service_irc  service_ssh  service_ssl  
0                  0             0            0            0            0  
1                  0             0            0            0            0  
2                  0             0            0            0            0  
3                  0             0            0            0            0  
4                  0             0            0            0            0  
...              ...           ...          ...          ...          ...  
2739669            0             0            0            0            0  
2739670            0             0            0            0            0  
2739671            0             0            0            0            0  
2739672            0             0            0            0            0  
2739673            0             0            0            0            0  

[2739674 rows x 34 columns]

In [4]:
del df['Unnamed: 0']

In [5]:
df['label'].value_counts()

1     1557534
2      522619
0      376965
4      262509
5       15152
6        4203
7         591
8          46
9          30
11         13
10          8
3           3
12          1
Name: label, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df[['duration', 'orig_bytes', 'resp_bytes', 'missed_bytes', 'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'proto_icmp', 'proto_tcp', 'proto_udp', 'service_-', 'service_dhcp', 'service_dns', 'service_http', 'service_ssh', 'service_ssl', 'service_irc', 'conn_state_OTH', 'conn_state_REJ', 'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR', 'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2', 'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR']].values

In [8]:
X.shape

(2739674, 31)

In [9]:
Y = pd.get_dummies(df['label']).values

In [10]:
Y

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=uint8)

In [11]:
#X = df[['duration', 'orig_bytes', 'resp_bytes', 'missed_bytes', 'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'proto_icmp', 'proto_tcp', 'proto_udp', 'conn_state_OTH', 'conn_state_REJ', 'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR', 'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2', 'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR']]
#Y = df[['label']]

In [12]:
X

array([[2.998796, 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ]])

In [13]:
df

duration  orig_bytes  resp_bytes  missed_bytes  orig_pkts  \
0        2.998796           0           0           0.0        3.0   
1        0.000000           0           0           0.0        1.0   
2        0.000000           0           0           0.0        1.0   
3        2.998804           0           0           0.0        3.0   
4        0.000000           0           0           0.0        1.0   
...           ...         ...         ...           ...        ...   
2739669  0.000000           0           0           0.0        1.0   
2739670  0.000000           0           0           0.0        1.0   
2739671  0.000000           0           0           0.0        1.0   
2739672  0.000000           0           0           0.0        1.0   
2739673  0.000000           0           0           0.0        1.0   

         orig_ip_bytes  resp_pkts  resp_ip_bytes  label category  ...  \
0                180.0        0.0            0.0      1  Malware  ...   
1                 60.0        0.0            0.0      1  Malware  ...   
2                 60.0        0.0            0.0      1  Malware  ...   
3                180.0        0.0            0.0      0   Benign  ...   
4                 60.0        0.0            0.0      0   Benign  ...   
...                ...        ...            ...    ...      ...  ...   
2739669           40.0        0.0            0.0      1  Malware  ...   
2739670           40.0        0.0            0.0      1  Malware  ...   
2739671           40.0        0.0            0.0      1  Malware  ...   
2739672           40.0        0.0            0.0      1  Malware  ...   
2739673           40.0        0.0            0.0      1  Malware  ...   

         conn_state_SF  conn_state_SH  conn_state_SHR  service_-  \
0                    0              0               0          1   
1                    0              0               0          1   
2                    0              0               0          1   
3                    0              0               0          1   
4                    0              0               0          1   
...                ...            ...             ...        ...   
2739669              0              0               0          1   
2739670              0              0               0          1   
2739671              0              0               0          1   
2739672              0              0               0          1   
2739673              0              0               0          1   

         service_dhcp  service_dns  service_http  service_irc  service_ssh  \
0                   0            0             0            0            0   
1                   0            0             0            0            0   
2                   0            0             0            0            0   
3                   0            0             0            0            0   
4                   0            0             0            0            0   
...               ...          ...           ...          ...          ...   
2739669             0            0             0            0            0   
2739670             0            0             0            0            0   
2739671             0            0             0            0            0   
2739672             0            0             0            0            0   
2739673             0            0             0            0            0   

         service_ssl  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
2739669            0  
2739670            0  
2739671            0  
2739672            0  
2739673            0  

[2739674 rows x 33 columns]

In [14]:
scaler = MinMaxScaler()

In [15]:
scaler.fit(X)

MinMaxScaler()

In [16]:
normalized_x = scaler.transform(X)

In [17]:
normalized_x

array([[8.16450401e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [18]:
normalized_x.shape

(2739674, 31)

In [19]:
scaler.fit(Y)

MinMaxScaler()

In [20]:
normalized_y = scaler.transform(Y)

In [21]:
normalized_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(normalized_x, normalized_y, random_state=10, test_size=0.2)

In [23]:
X_train.shape

(2191739, 31)

In [26]:
model = Sequential()

In [27]:
model.add(Dense(1024, activation='relu',input_dim=31))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(13, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [28]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 1024)              32768     
_________________________________________________________________
dense_7 (Dense)              (None, 512)               524800    
_________________________________________________________________
dropout_4 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 256)               131328    
_________________________________________________________________
dropout_5 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 128)               32896     
_________________________________________________________________
dropout_6 (Dropout)          (None, 128)              

In [29]:
import time

In [30]:
start = time.time()
print('program start...')
print()

history = model.fit(X_train, Y_train, epochs = 20, batch_size=16, validation_data=(X_test,Y_test),verbose=1)

print()
end = time.time()
print('program end...')
print()
print('time cost: ')
print(end - start, 'seconds')

program start...

Epoch 1/20
136984/136984 [==============================] - 211s 2ms/step - loss: 0.8669 - accuracy: 0.6845 - val_loss: 0.8635 - val_accuracy: 0.6855
Epoch 2/20
136984/136984 [==============================] - 211s 2ms/step - loss: 0.8660 - accuracy: 0.6846 - val_loss: 0.8613 - val_accuracy: 0.6855
Epoch 3/20
136984/136984 [==============================] - 211s 2ms/step - loss: 0.8674 - accuracy: 0.6846 - val_loss: 0.8609 - val_accuracy: 0.6855
Epoch 4/20
  3528/136984 [..............................] - ETA: 3:11 - loss: 0.8678 - accuracy: 0.6807

KeyboardInterrupt: 